### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#132]
## Consider `grad.then()` features that can together serve as MVP.

**Focus Points**:

- [ ] Front End 
    - [ ] Add items here

- [ ] Back End 
    - [ ] Add items here

- [ ] Database 
    - [ ] Add items here

- [ ] Deployment 
    - [x] Temporarily using `gh-pages`

**Comment by mar-bi** [comment]
##  Next `grad.then()` features that can together serve as MVP in **Voyage-4**.

**Focus Points**:

- [ ] Front End 
  - [x] Main, Jobs, Learn, Events, Support, Stories pages 
  - [ ] Page for adding user content
  - [x] Page for reading the whole story
  - [ ] Page for user authentication
  - [ ] **data** layer is managed by `Apollo` qraphql client
  - [ ] **app state** is managed by `apollo-link-state` (instead of Redux`)
  - [ ]  all app's pages have real content (data from 3-rd party API's or our DB)
  - [ ] Testing UI components
---
- [ ] Back End 
    - [ ] qraphQl server
---
- [ ] Database 
    - [ ] `prisma` or `graphcool` backend DB
---
- [ ] Deployment 
    - [x] Temporarily using `gh-pages`
    - [ ] Move from `gh-pages` to ...

**Comment by mar-bi** [comment]
# `grad.then()` features that can together serve as MVP in Voyage-6.

## Front End
- [ ] **Pages**
  - [x] Main, Jobs, Learn, Events, Support, Stories pages;
  - [ ] Page for adding user content;
  - [x] Page for reading the whole story;
  - [ ] Page for user authentication.
___
- [ ] **Data**
  - [ ] ??? the app state is managed by **React Context API** (or Redux);
  - [ ] ??? data layer is managed by **Apollo qraphql client**;
  - [ ]  `Jobs` page has real content (data from 3-rd party API's or our DB);
  - [x] `Stories` page has real content.
___
- [ ] **Testing UI components**
  - [ ] test for every component;
  - [ ] good coverage.

## Back End
 - [ ] ??? qraphQl server;
 - [x] headless **Contentful** backend.

## Database
 - [ ] ??? prisma or graphcool backend DB.

## Deployment
  ### Front-end
  - [x] gh-pages;
  - [ ] Move from gh-pages to ...
  
### Back-end and DB
 - [ ] ??? host for back-end.
